use dp03;

-- adding brand name column for better insights
ALTER TABLE CARS24
ADD COLUMN brand_name VARCHAR(255);

UPDATE CARS24
SET brand_name = SUBSTRING_INDEX(name, ' ', 1);

SELECT *
FROM CARS24;

-- Cars with Low Mileage but High Power Output
SELECT COUNT(*) AS total_cars
FROM cars24;

-- distribution of fuel types 

SELECT fuel, COUNT(*) AS fuel_count
FROM cars24
GROUP BY fuel
ORDER BY fuel_count DESC;

-- Top 5 cars with highest engine power
SELECT name, max_power
FROM cars24
ORDER BY max_power DESC
LIMIT 5;

-- Calculate the Total Revenue Generated by Each Car Model.
SELECT name, COUNT(*) AS total_sold, AVG(selling_price) AS avg_selling_price, SUM(selling_price) AS total_revenue
FROM CARS24
GROUP BY name
ORDER BY total_revenue DESC;

-- no of cars sold each year 
SELECT year, COUNT(*) AS car_count
FROM cars24
GROUP BY year
ORDER BY year;

Select transmission ,count(*) as transmission_count
from cars24
group by transmission;

-- no of cars with different tyes of selller
SELECT seller_type, COUNT(*) AS seller_count
FROM cars24
GROUP BY seller_type;

-- Calculate the average engine displacement (CC) by fuel type
SELECT fuel, AVG(engine_cc) AS avg_engine_cc
FROM cars24
GROUP BY fuel;



--  Average Kilometers Driven by Cars in the Dataset
SELECT AVG(km_driven) AS avg_km_driven
FROM cars24;


-- car models that are sold by individual sellers and have driven the least number of km
SELECT name, km_driven
FROM CARS24
ORDER BY km_driven ASC
LIMIT 5;


-- Count the number of cars by the number of seats
SELECT name,seats
FROM cars24
GROUP BY  name ,seats
ORDER BY seats;

-- Average Selling Price for Cars Sold by Different Types of Sellers
SELECT seller_type, AVG(selling_price) AS avg_price
FROM CARS24
GROUP BY seller_type;

-- Identify the Most Fuel-Efficient Car Models
SELECT name, MAX(mileage) AS max_mileage
FROM CARS24
GROUP BY name
ORDER BY max_mileage DESC
LIMIT 5;



-- Average Selling Price Difference Between Manual and Automatic Transmission
SELECT 'Manual' AS transmission_type, AVG(selling_price) AS avg_selling_price
FROM cars24
WHERE transmission = 'Manual'
UNION ALL
SELECT 'Automatic' AS transmission_type, AVG(selling_price) AS avg_selling_price
FROM cars24
WHERE transmission = 'Automatic';

--  Car Model with the Largest Engine Displacement
SELECT name, `engine [CC]`
FROM CARS24
ORDER BY `engine [CC]` DESC
LIMIT 1;

-- Most Expensive Hyundai Car Model
SELECT name, selling_price
FROM CARS24
WHERE name LIKE '%Hyundai%'
ORDER BY selling_price DESC
LIMIT 1;

 -- Percentage of "First Owner" Cars in the Dataset
 SELECT (COUNT(*) / (SELECT COUNT(*) FROM CARS24)) * 100 AS percentage
FROM CARS24
WHERE owner = 'First Owner';

 -- Car Models with the Most "Fourth & Above Owner" Cars
 SELECT name, COUNT(*) AS car_count
FROM CARS24
WHERE owner = 'Fourth & Above Owner'
GROUP BY name
ORDER BY car_count DESC;




-- Total Selling Price for Each Transmission Type and Fuel Type Combination
SELECT transmission, fuel, SUM(selling_price) AS total_price
FROM CARS24
GROUP BY transmission, fuel;


-- fuel Efficiency Across Different Car Models
SELECT name, AVG(mileage) AS avg_mileage
FROM CARS24
GROUP BY name
ORDER BY avg_mileage DESC;



-- top 3 car models with the highest selling prices that were manufactured before 2010.

SELECT name, selling_price,year 
FROM CARS24
WHERE year < 2010
ORDER BY selling_price DESC
LIMIT 3;

-- total number of cars sold in each year, along with the total revenue generated in that year.
SELECT year, COUNT(*) AS total_cars_sold, SUM(selling_price) AS total_revenue
FROM CARS24
GROUP BY year
ORDER BY year;

-- Average selling price by brand type 

SELECT 
    brand_name,
    AVG(selling_price) AS avg_selling_price
FROM 
    CARS24
GROUP BY 
    brand_name;



-- Total Number of Cars Sold by Trustmark Dealers by Year
SELECT seller_type, YEAR AS sales_year, COUNT(*) AS car_count
FROM CARS24
WHERE seller_type = 'Trustmark Dealer'
GROUP BY seller_type, sales_year;  

-- calculate yearly  sales, average sales, and highest sale per year
SELECT
    year,
    SUM(selling_price) AS total_sales,
    AVG(selling_price) AS average_sales,
    MAX(selling_price) AS highest_sale
FROM
    CARS24
GROUP BY
    year
ORDER BY
    year;




-- Summary Statistics 
SELECT
  COUNT(*) AS total_cars,
  AVG(selling_price) AS avg_price,
  MIN(selling_price) AS min_price,
  MAX(selling_price) AS max_price,
  STDDEV(selling_price) AS std_dev_price,
  MAX(mileage) AS max_mileage,
  STDDEV(mileage) AS std_dev_mileage,
  MAX(km_driven) AS max_km_driven,
  STDDEV(km_driven) AS std_dev_km_driven,
  MAX(`engine [CC]`) AS max_engine_displacement,
  STDDEV(`engine [CC]`) AS std_dev_engine_displacement,
  MAX(seats) AS max_seats,
  STDDEV(seats) AS std_dev_seats
FROM CARS24;








